FROM python:3.10-slim

WORKDIR /bookstore

ADD ./ /bookstore/

RUN apt-get update \
    && apt-get -y install python3-dev default-libmysqlclient-dev build-essential pkg-config

RUN pip install --upgrade pip

RUN pip install -r requirements.txt



WORKDIR /bookstore/store
